### PR TITLE
added vs. JS Function Currying

### PR DESCRIPTION
**Pull request by semmel**
Although very much like partial application I think currying is 
* a bit more general and
* `hof::partial` is really currying with partial application

### CODE REVIEW

**Comment by JohnMurray** [comment]
Thank you for the pull request! Some initial feedback is that since Lodash already has a `curry` function, I think it might make sense to use that in the examples so that users of JS only have to look at one library and I've tried to find the most popular one so the most amount of people will be familiar with it. Ramada seems popular (at 13k stars) but lodash is significantly more so (at 33k stars).

**Comment by semmel** [comment]
Thanks for the review!
I've addressed most of it in the second commit. Just two remarks:
*  Concerning the JS library where we take curry from: As suggested I changed to Lodash but with a remark, that for Function Programming in JS there are better alternatives (in particular lodash/fp). I don't want to give false advise here for people looking the other way to learn JavaScript coming from C++.
* I added a small section on C++ `auto`, because
    * if I had to remove it, the C++ solution would look very different from the JS part, and
    * it would have taken some time to come up with the proper templated functions: It's easier to write for me.

Furthermore I felt that hand-writing `curry2` looked so similar in C++ and JS that it had to be included. Also it demystifies currying for beginner programmers.

**Comment by semmel** [comment]
Glad you accepted :-)

**Comment by JohnMurray** [comment]
Absolutely! Thank you for contributing! :smile:  I'll add a ticket to add a "contributors" link on the site. Honestly, I hadn't expected anyone to find, much less contribute to the project before it was "officially announced."

**Pull request merged**
